### PR TITLE
feature: columnOffset

### PR DESCRIPTION
**Pull request by russmatney**
Ran into a csv with a header today (it's actually an excel doc that i'm parsing via [excel-stream](https://github.com/dominictarr/excel-stream)). An offset that still allows the use of the column names would be ideal. Added two tests to cover it – let me know if you'd like anything else before a merge.

### CODE REVIEW

**Comment by russmatney** [comment]
Just noticed I didn't follow your commit style - let me know if you want me to squash/rebase and open a new PR.

**Comment by russmatney** [comment]
@lbdremy ping - would love for this to be merged whenever you get a minute.

**Comment by lbdremy** [comment]
Sure my bad.

**Comment by lbdremy** [comment]
I will publish to npm tonight.

**Comment by russmatney** [comment]
No worries! Thanks a ton!

**Comment by russmatney** [comment]
@lbdremy - thanks for the merge - no rush, just pinging for an `npm publish` whenever you get a moment. Am referencing this via github and a commit hash right now, i.e.:

```
"csv-stream": "git://github.com/lbdremy/node-csv-stream.git#572925e0ce40134ad591fec4d4606ec378740b15"
```

**Pull request merged**
